### PR TITLE
feat(config): added test config

### LINKED ISSUE #162: [FEATURE]refactoring tests

### PR DESCRIPTION
**Pull request by DramaTourG**
**What**

- added config for tests
- upgraded test. get_slot_by_filter

related to #162

### CODE REVIEW

**Review by glebhg — CHANGES_REQUESTED** [review]
Please, explain why do we need to do this

**Comment by DramaTourG** [comment]
> Please, explain why do we need to do this

because now the test config is not working. it cleared up when flask-mail was added.

**Comment by DramaTourG** [comment]
> Please, explain why do we need to do this

and this will help us create app with a specific config for end-to-end tests.

**Review by eduard-terletskiy — DISMISSED** [review]

**Review by eduard-terletskiy — APPROVED** [review]

**Comment by DramaTourG** [comment]
> Please, explain why do we need to do this

@glebhg can it merge?

**Review by glebhg — APPROVED** [review]

**Pull request merged**
